version: "3.8"

services:
  meshsense:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshsense
    ports:
      - "5920:5920"  # API port
    environment:
      #- ADDRESS=192.168.9.231
      - PORT=5920
      - ACCESS_KEY=changeme
      - DEV_UI_URL=http://localhost:5921
      - DISPLAY=:99  # Required for headless Electron
    cap_add:
      - NET_ADMIN  # For network operations
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0  # Raspberry Pi Bluetooth
      - /dev/serial/by-id:/dev/serial/by-id
    volumes:
      - meshsense-data:/home/mesh/.meshsense
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5920/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    user: "1000:1000"  # Matches Dockerfile UID
    labels:
      - "project=meshsense"

volumes:
  meshsense-data:
