version: "3.8"

services:
  meshsense-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meshsense-webui
    ports:
      - "5920:5920"
    environment:
      - ADDRESS=192.168.9.231 # # The IP address of your Meshtastic node
      - PORT=5920  # The port you will use to access the Meshsense web UI
      - HOST=0.0.0.0 # The host you will use to access the Meshsense web UI (in the container)
      - ACCESS_KEY=changeme
      - NATIVEBUILD=true # Helps determine if we're on a native ARM64 system
    tty: true
    stdin_open: true
    cap_add:
      - SYS_ADMIN       # Required for sandboxing
      - SYS_CHROOT      # Needed for namespace operations
    security_opt:
      - seccomp:unconfined  # Allow syscalls needed by Chromium
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
    #  - /dev/serial/by-id:/dev/serial/by-id
    volumes:
      - ./meshsense-data:/home/mesh/.meshsense
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro      
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5921/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    user: "1000:1000"
    labels:
      - "project=meshsense"
